#! /bin/bash

# set to "echo" for debugging
#
DEBUG=""

CMDS="on|off|cycle"

# usage
#
usage() {
    echo "$*"
    echo "usage:"
    echo "$0 [target] [$CMDS]"
    echo "   where TARGET is the hostname of the target device (we find the PDU port)"
    exit 1
}

# The PDU associations
#

declare -A pdu
pdu[spine-1-1]=45
pdu[spine-1-2]=44
pdu[leaf-1-1]=43
pdu[leaf-1-2]=42
pdu[leaf-2-1]=41
pdu[leaf-2-2]=40
pdu[leaf-s-1]=39
pdu[leaf-s-2]=38
pdu[server-1-1]=37
pdu[server-1-2]=36
pdu[server-1-3]=8
pdu[server-1-4]=7
pdu[server-2-1]=35
pdu[server-2-2]=34
pdu[server-2-3]=6
pdu[server-2-4]=3
pdu[server-s-1]=33
pdu[server-s-2]=5
pdu[sdr]=24


# quick error checking
#
sudo ls &> /dev/null || usage "You do not seem to have sudo access"
[ $# -ge 2 ] || usage "You did not specify enough comand line arguments"

# get the target
#

PORT=${pdu[$1]}
if [ "n${PORT}" == "n" ]; then
  usage "$1 does not seem to have a pdu control point"
else
  echo "targeting PDU port for ${1}"
  shift
fi

# main
#

SNMPSET="sudo snmpset -v 1 -c bP6*EZqd pdu2l 1.3.6.1.4.1.1718.3.2.3.1.11.1.1.${PORT}"

for I in $*
do
  case $I in
    on)    ${DEBUG} ${SNMPSET} i 1;;
    off)   ${DEBUG} ${SNMPSET} i 2;;
    cycle) ${DEBUG} ${SNMPSET} i 2
	   sleep 5
           ${DEBUG} ${SNMPSET} i 1;;
    *)     usage "\"${I}\" is not one of $CMDS";;
  esac
done

