---
# Setup the OAM network and configuration manager
#
#
#

- name: VCO OAM Setup
  hosts: localhost
  gather_facts: False

- name: Create project
  import_playbook: oam_layer/project.yml
  
- name: Create networks
  import_playbook: oam_layer/networks.yml

#    - import_playbook: oam_layer/tower.yml
#    - import_playbook: oam_layer/worker.yml
