apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-image-registry 
spec:
  capacity:
    storage: 100Gi 
  accessModes:
  - ReadWriteMany 
  nfs: 
    path: /opt/nfs/image-registry  
    server: 192.168.1.1
  persistentVolumeReclaimPolicy: Retain 