kind: Template
apiVersion: v1
objects:
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: tiller

- kind: Role
  apiVersion: v1
  metadata:
    name: tiller
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - create
    - get
    - list
    - update
    - delete
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get

- kind: RoleBinding
  apiVersion: v1
  metadata:
    name: tiller
  roleRef:
    name: tiller
    namespace: ${TILLER_NAMESPACE}
  subjects:
  - kind: ServiceAccount
    name: tiller

parameters:
- name: HELM_VERSION
  value: v2.14.1
  required: true
- name: TILLER_NAMESPACE
  value: tiller
  required: true