---
- name: Register Controller and Compute nodes
  hosts: controllers,computes
  become: yes
  vars:
    repos:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-rh-common-rpms
      - rhel-ha-for-rhel-7-server-rpms
      - rhel-7-server-openstack-13-rpms
      - rhel-7-server-rhceph-3-mon-rpms
  tasks:
    - name: Register system
      redhat_subscription:
        autosubscribe: no
        activationkey: vCOv2-OSP13 # make sure auto attach is DISABLED
        org_id: <INPUT>
        pool_ids: 8a85f98c5fdd23ab015fdef579082046 
    - name: Disable all repos
      command: "subscription-manager repos --disable *"
    - name: Enable Controller and Compute node repos
      command: "subscription-manager repos --enable {{ item }}"
      with_items: "{{ repos }}"
- name: Register Ceph-storage nodes
  hosts: storages
  become: yes
  vars:
    repos:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-rh-common-rpms
      - rhel-ha-for-rhel-7-server-rpms
      - rhel-7-server-openstack-13-rpms
      - rhel-7-server-rhceph-3-mon-rpms
      - rhel-7-server-rhceph-3-osd-rpms
  tasks:
    - name: Register system
      redhat_subscription:
        autosubscribe: no
        activationkey: vCOv2-OSP13 #make sure auto attach is DISABLED
        org_id: <INPUT>
        pool_ids: 
          - 8a85f98b6207bd3e016209a0e0520944
          - 8a85f98c5fdd23ab015fdef579082046
    - name: Disable all repos
      command: "subscription-manager repos --disable *"
    - name: Enable Ceph-Storage node repos
      command: "subscription-manager repos --enable {{ item }}"
      with_items: "{{ repos }}"
